"""
Chart Executor Service
Safely executes matplotlib/seaborn code generated by the visualization agent.
"""
import pandas as pd
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import seaborn as sns
import re
import uuid
from pathlib import Path
from typing import Optional, Tuple

# Chart output directory
CHARTS_DIR = Path("uploads/charts")
CHARTS_DIR.mkdir(parents=True, exist_ok=True)

# Set premium theme
plt.style.use('dark_background')


def clean_agent_code(code: str) -> str:
    """
    Clean up agent-generated code to make it executable.
    """
    # Remove markdown code blocks
    code = re.sub(r'```python\s*', '', code)
    code = re.sub(r'```\s*', '', code)
    
    # Remove any leading/trailing whitespace
    code = code.strip()
    
    # Remove plt.show() calls
    code = re.sub(r'plt\.show\(\)', '', code)
    
    # Remove any import statements (we provide them)
    lines = code.split('\n')
    cleaned_lines = []
    for line in lines:
        stripped = line.strip()
        if stripped.startswith('import ') or stripped.startswith('from '):
            continue
        cleaned_lines.append(line)
    
    return '\n'.join(cleaned_lines)


def execute_chart_code(code: str, df: pd.DataFrame) -> Tuple[Optional[str], Optional[str]]:
    """
    Execute visualization code safely and return the path to the generated chart.
    """
    # Clean the agent's code
    cleaned_code = clean_agent_code(code)
    
    if not cleaned_code.strip():
        return None, "No valid code to execute"
    
    # Close any existing figures
    plt.close('all')
    
    # Create execution environment with data available
    local_env = {
        'df': df,
        'pd': pd,
        'np': np,
        'plt': plt,
        'sns': sns,
    }
    
    # Set up the environment
    plt.style.use('dark_background')
    sns.set_theme(style="darkgrid", palette="viridis")
    
    try:
        # Create default figure first
        fig, ax = plt.subplots(figsize=(10, 6))
        local_env['fig'] = fig
        local_env['ax'] = ax
        
        # Execute the cleaned code
        exec(cleaned_code, local_env)
        
        # Get the current figure
        fig = plt.gcf()
        
        if fig.get_axes():
            # Apply dark styling
            fig.patch.set_facecolor('#0a0a0a')
            for axis in fig.get_axes():
                axis.set_facecolor('#0a0a0a')
                axis.tick_params(colors='white')
                for spine in axis.spines.values():
                    spine.set_color('#444')
            
            # Save the figure
            filename = f"agent_{uuid.uuid4().hex[:8]}.png"
            filepath = CHARTS_DIR / filename
            fig.savefig(filepath, dpi=120, bbox_inches='tight', 
                       facecolor='#0a0a0a', edgecolor='none')
            plt.close('all')
            return f"/charts/{filename}", None
        else:
            plt.close('all')
            return None, "No figure was created by the code"
            
    except SyntaxError as e:
        plt.close('all')
        return None, f"Syntax error in generated code: {str(e)}"
    except Exception as e:
        plt.close('all')
        return None, f"Error executing chart code: {str(e)}"


def generate_simple_chart(df: pd.DataFrame, chart_type: str, column: str, 
                          color: str = "#6366f1", title: str = None) -> Tuple[Optional[str], Optional[str]]:
    """
    Generate a simple chart without code execution.
    Direct and reliable fallback.
    """
    plt.close('all')
    
    try:
        fig, ax = plt.subplots(figsize=(10, 6))
        plt.style.use('dark_background')
        
        if chart_type == "histogram":
            data = df[column].dropna()
            ax.hist(data, bins=30, color=color, edgecolor='white', alpha=0.8)
            ax.set_xlabel(column, color='white')
            ax.set_ylabel('Frequency', color='white')
            
        elif chart_type == "bar":
            value_counts = df[column].value_counts().head(10)
            colors = plt.cm.viridis(np.linspace(0.3, 0.9, len(value_counts)))
            ax.barh(value_counts.index.astype(str), value_counts.values, color=colors)
            ax.invert_yaxis()
            ax.set_xlabel('Count', color='white')
            
        elif chart_type == "pie":
            value_counts = df[column].value_counts().head(8)
            colors = plt.cm.viridis(np.linspace(0.2, 0.9, len(value_counts)))
            ax.pie(value_counts.values, labels=value_counts.index.astype(str), 
                  colors=colors, autopct='%1.1f%%', startangle=90,
                  textprops={'color': 'white'})
            ax.axis('equal')
            
        elif chart_type == "scatter" and ',' in column:
            cols = [c.strip() for c in column.split(',')]
            if len(cols) >= 2:
                ax.scatter(df[cols[0]], df[cols[1]], alpha=0.6, color=color)
                ax.set_xlabel(cols[0], color='white')
                ax.set_ylabel(cols[1], color='white')
        
        ax.set_title(title or f"{chart_type.title()} of {column}", fontweight='bold', color='white')
        
        # Apply dark styling
        fig.patch.set_facecolor('#0a0a0a')
        ax.set_facecolor('#0a0a0a')
        ax.tick_params(colors='white')
        for spine in ax.spines.values():
            spine.set_color('#444')
        
        # Save
        filename = f"simple_{uuid.uuid4().hex[:8]}.png"
        filepath = CHARTS_DIR / filename
        fig.savefig(filepath, dpi=120, bbox_inches='tight', 
                   facecolor='#0a0a0a', edgecolor='none')
        plt.close('all')
        
        return f"/charts/{filename}", None
        
    except Exception as e:
        plt.close('all')
        return None, str(e)
